-- MySQL Script generated by MySQL Workbench
-- Mon Feb  8 15:28:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema techstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techstore` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `techstore` ;

-- -----------------------------------------------------
-- Table `techstore`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`clients` (
  `clientID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(25) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `createdBy` VARCHAR(45) NULL DEFAULT NULL,
  `createdOn` TIMESTAMP(6) NULL DEFAULT NULL,
  `modifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`clientID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `techstore`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`employees` (
  `employeesID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `dateofbirth` DATE NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(25) NULL DEFAULT NULL,
  `role` VARCHAR(25) NULL DEFAULT NULL,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `salary` INT NULL DEFAULT NULL,
  `createdBy` VARCHAR(25) NULL DEFAULT NULL,
  `createdOn` TIMESTAMP(6) NULL DEFAULT NULL,
  `modifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`employeesID`),
  UNIQUE INDEX `User_UNIQUE` (`user` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `techstore`.`cartels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`cartels` (
  `cartelID` INT NOT NULL AUTO_INCREMENT,
  `dataCreated` INT NULL DEFAULT NULL,
  `employeesId` INT NOT NULL,
  `clientID` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL DEFAULT NULL,
  `createdOn` TIMESTAMP(6) NULL DEFAULT NULL,
  `modifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cartelID`),
  INDEX `fk_Cartel_emploee1_idx` (`employeesId` ASC) VISIBLE,
  INDEX `fk_Cartel_Client1_idx` (`clientID` ASC) VISIBLE,
  CONSTRAINT `fk_Cartel_Client1`
    FOREIGN KEY (`clientID`)
    REFERENCES `techstore`.`clients` (`clientID`),
  CONSTRAINT `fk_Cartel_emploee1`
    FOREIGN KEY (`employeesId`)
    REFERENCES `techstore`.`employees` (`employeesID`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `techstore`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`suppliers` (
  `supplierID` INT NOT NULL AUTO_INCREMENT,
  `supplierCompanyName` VARCHAR(45) NULL DEFAULT NULL,
  `product` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `createdBy` VARCHAR(45) NULL DEFAULT NULL,
  `createdOn` TIMESTAMP(6) NULL DEFAULT NULL,
  `modifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`supplierID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `techstore`.`computers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`computers` (
  `computerID` INT NOT NULL AUTO_INCREMENT,
  `computerName` VARCHAR(45) NULL DEFAULT NULL,
  `computerType` VARCHAR(45) NULL DEFAULT NULL,
  `isbn` VARCHAR(45) NULL DEFAULT NULL,
  `dateofPublication` DATETIME NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `createdBy` VARCHAR(45) NULL DEFAULT NULL,
  `createdOn` TIMESTAMP(6) NULL DEFAULT NULL,
  `modifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  `suppliers_supplierID` INT NOT NULL,
  PRIMARY KEY (`computerID`),
  UNIQUE INDEX `ISBN_UNIQUE` (`isbn` ASC) VISIBLE,
  INDEX `fk_computers_suppliers1_idx` (`suppliers_supplierID` ASC) VISIBLE,
  CONSTRAINT `fk_computers_suppliers1`
    FOREIGN KEY (`suppliers_supplierID`)
    REFERENCES `techstore`.`suppliers` (`supplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `techstore`.`cartelrecords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techstore`.`cartelrecords` (
  `cartelRecordID` INT NOT NULL AUTO_INCREMENT,
  `dataStarted` DATETIME NULL DEFAULT NULL,
  `endData` DATETIME NULL DEFAULT NULL,
  `createData` VARCHAR(45) NULL DEFAULT NULL,
  `computersID` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL DEFAULT NULL,
  `createdOn` TIMESTAMP(6) NULL DEFAULT NULL,
  `modifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  `cartelId` INT NOT NULL,
  PRIMARY KEY (`cartelRecordID`),
  INDEX `fk_CartelRecords_computers1_idx` (`computersID` ASC) VISIBLE,
  INDEX `fk_cartel_idx` (`cartelId` ASC) VISIBLE,
  CONSTRAINT `fk_cartel`
    FOREIGN KEY (`cartelId`)
    REFERENCES `techstore`.`cartels` (`cartelID`),
  CONSTRAINT `fk_CartelRecords_computers1`
    FOREIGN KEY (`computersID`)
    REFERENCES `techstore`.`computers` (`computerID`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
